/**
 * Copyright 2026 玑渡 GIDO Contributors
 * SPDX-License-Identifier: Apache-2.0
 */

const SENSITIVE_KEY = /(password|passwd|secret|token|credential|access[_-]?key|private[_-]?key|client[_-]?secret)/i
const REDACTED = '******'

export function redactPipelineText(value: string): string {
  return value
    .replace(/([a-z][a-z0-9+.-]*:\/\/[^:\s/@]+:)([^@\s/]+)(@)/gi, `$1${REDACTED}$3`)
    .replace(/(['"]?(?:password|passwd|secret|token|access[_-]?key|client[_-]?secret)['"]?\s*[=:]\s*)(['"]?)([^'",;\s}]+)\2/gi, `$1'${REDACTED}'`)
    .replace(/((?:PASSWORD|TOKEN|SECRET|ACCESS_KEY)\s+)(\S+)/gi, `$1${REDACTED}`)
}

export function sanitizePipelineArtifact<T>(value: T): T {
  if (Array.isArray(value)) {
    return value.map(item => sanitizePipelineArtifact(item)) as T
  }
  if (value && typeof value === 'object') {
    const output: Record<string, unknown> = {}
    Object.entries(value as Record<string, unknown>).forEach(([key, item]) => {
      output[key] = SENSITIVE_KEY.test(key) ? REDACTED : sanitizePipelineArtifact(item)
    })
    return output as T
  }
  return (typeof value === 'string' ? redactPipelineText(value) : value) as T
}

export type PipelineMode = 'append' | 'upsert' | 'cdc'

export function pipelineModeMeta(mode: PipelineMode) {
  if (mode === 'cdc') {
    return { label: 'CDC', color: 'purple', description: '消费完整变更日志；必须配置主键并确认状态兼容。' }
  }
  if (mode === 'upsert') {
    return { label: 'Upsert', color: 'blue', description: '按主键更新目标记录；删除语义取决于源变更日志。' }
  }
  return { label: 'Append', color: 'green', description: '仅追加写入；不处理更新与删除。' }
}

export function buildLocalPipelineExplain(config: Record<string, any>) {
  const mode = (config.mode || 'append') as PipelineMode
  const columns = Array.isArray(config.schema?.columns) ? config.schema.columns : []
  const mapped = Array.isArray(config.mapping?.fields) ? config.mapping.fields : []
  const sink = config.sink || {}
  const source = config.source || {}
  const selectList = mapped.length
    ? mapped.map((field: any) => `  ${field.expression || `\`${field.source || field.target}\``} AS \`${field.target}\``).join(',\n')
    : columns.map((field: any) => `  \`${field.name}\``).join(',\n')
  const primaryKeys = Array.isArray(sink.primary_keys) ? sink.primary_keys : []
  const sourceName = source.table || 'source_table'
  const targetName = `${sink.database || 'default'}.\`${sink.table || 'target_table'}\``
  const artifact = [
    '-- Generated by GIDO Pipeline Console (redacted preview)',
    `-- Source credential: \${secret:${source.credential_ref || 'credential-reference-required'}}`,
    `-- Write semantics: ${mode.toUpperCase()}`,
    `INSERT INTO ${targetName}`,
    `SELECT\n${selectList || '  *'}`,
    `FROM \`${sourceName}\`;`,
  ].join('\n')

  const risks = [
    ...(mode === 'append' ? [] : [{ code: 'STATEFUL_WRITE', level: 'high', message: `${mode.toUpperCase()} 会维护主键状态，升级前需验证 Savepoint 兼容性。`, requires_confirmation: true }]),
    ...(mode !== 'append' && primaryKeys.length === 0 ? [{ code: 'PRIMARY_KEY_REQUIRED', level: 'blocker', message: 'Upsert / CDC 必须配置 Paimon 主键。', requires_confirmation: false }] : []),
    ...(config.schema?.evolution === 'auto' ? [{ code: 'AUTO_SCHEMA_EVOLUTION', level: 'medium', message: '自动 Schema 演进可能新增目标列。', requires_confirmation: true }] : []),
  ]

  return sanitizePipelineArtifact({
    generated_artifact: {
      kind: 'flink_sql',
      content: artifact,
      runner: {
        type: 'flink_sql',
        secret_resolution: 'runtime_profile_refs',
        source_connection_profile_id: source.connection_profile_id,
        sink_connection_profile_id: sink.connection_profile_id,
      },
      redacted: true,
    },
    schema_diff: columns.map((field: any) => ({ column: field.name, change: 'ADD_IF_MISSING', type: field.type })),
    placement: {
      decision: config.placement?.pool ? `调度到资源池 ${config.placement.pool}` : '使用工作空间默认资源池',
      resource_tier: config.runtime?.resource_tier || 'platform-default',
      parallelism: config.runtime?.parallelism || 1,
    },
    risks,
    valid: !risks.some(risk => risk.level === 'blocker'),
    local_fallback: true,
  })
}
