# Copyright 2026 玑渡 GIDO Contributors
# SPDX-License-Identifier: Apache-2.0
"""Ad-hoc SQL execution handles, server timeouts and safe cancellation."""
from __future__ import annotations

import logging
import threading
from contextlib import contextmanager
from dataclasses import asdict, dataclass
from typing import Any, Dict, Iterator, Optional

from app.models.workspace import DataSource
from app.services.integration_runtime import normalize_ds_type, open_connection

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class ExecutionBinding:
    run_id: int
    lease_token: str
    statement_index: int

    @property
    def tag(self) -> str:
        # The token is generated by the worker, never supplied by an API client.
        return f"gido-adhoc:{self.run_id}:{self.lease_token}:{self.statement_index}"


@dataclass
class CancelResult:
    requested: bool
    confirmed: bool
    method: str
    reason: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class _Handle:
    binding: ExecutionBinding
    ds_type: str
    connection: Any


_registry_lock = threading.Lock()
_registry: Dict[ExecutionBinding, _Handle] = {}


def _execute_quietly(cursor: Any, sql: str, params: Any = None) -> bool:
    try:
        cursor.execute(sql, params) if params is not None else cursor.execute(sql)
        return True
    except Exception:
        logger.debug("optional ad-hoc SQL session setting failed: %s", sql, exc_info=True)
        return False


def _configure_session(kind: str, conn: Any, binding: ExecutionBinding, timeout_seconds: int) -> None:
    cur = conn.cursor()
    try:
        timeout_ms = max(1, int(timeout_seconds)) * 1000
        if kind == "postgresql":
            _execute_quietly(cur, "SET application_name = %s", (binding.tag,))
            _execute_quietly(cur, "SET statement_timeout = %s", (timeout_ms,))
        else:
            # MySQL uses milliseconds for MAX_EXECUTION_TIME. Doris uses seconds
            # for query_timeout and safely ignores the unsupported MySQL setting.
            _execute_quietly(cur, f"SET SESSION MAX_EXECUTION_TIME = {timeout_ms}")
            _execute_quietly(cur, f"SET query_timeout = {max(1, int(timeout_seconds))}")
    finally:
        cur.close()


@contextmanager
def registered_connection(
    ds: DataSource,
    binding: ExecutionBinding,
    *,
    timeout_seconds: int,
) -> Iterator[tuple]:
    """Open and register a connection under a worker-owned execution identity."""
    with open_connection(ds) as opened:
        kind, conn = opened[0], opened[1]
        _configure_session(kind, conn, binding, timeout_seconds)
        handle = _Handle(binding=binding, ds_type=normalize_ds_type(ds), connection=conn)
        with _registry_lock:
            _registry[binding] = handle
        try:
            yield opened
        finally:
            with _registry_lock:
                if _registry.get(binding) is handle:
                    _registry.pop(binding, None)


@contextmanager
def statement_handle(
    connection: Any,
    ds_type: str,
    binding: ExecutionBinding,
) -> Iterator[None]:
    """Bind the currently executing statement to its exact statement index."""
    handle = _Handle(binding, (ds_type or "").strip().lower(), connection)
    if handle.ds_type == "postgresql":
        cur = connection.cursor()
        try:
            _execute_quietly(cur, "SET application_name = %s", (binding.tag,))
        finally:
            cur.close()
    with _registry_lock:
        _registry[binding] = handle
    try:
        yield
    finally:
        with _registry_lock:
            if _registry.get(binding) is handle:
                _registry.pop(binding, None)


def _cancel_local(binding: ExecutionBinding) -> Optional[CancelResult]:
    with _registry_lock:
        handle = _registry.get(binding)
    if not handle:
        return None
    try:
        if handle.ds_type == "postgresql":
            handle.connection.cancel()
        else:
            # PyMySQL cannot send KILL over the same socket while another
            # thread is blocked reading that query. Closing the registered
            # socket is the reliable same-process interrupt; replicas use a
            # separate control connection below.
            handle.connection.close()
        return CancelResult(True, True, "same_process")
    except Exception as exc:
        logger.warning("local SQL cancel failed run=%s", binding.run_id, exc_info=True)
        return CancelResult(True, False, "same_process", str(exc)[:500])


def cancel_execution(ds: DataSource, binding: ExecutionBinding) -> CancelResult:
    """Cancel locally, or discover the tagged query through a control connection."""
    local = _cancel_local(binding)
    if local and local.confirmed:
        return local

    kind = normalize_ds_type(ds)
    try:
        with open_connection(ds) as opened:
            conn = opened[1]
            cur = conn.cursor()
            try:
                if kind == "postgresql":
                    cur.execute(
                        "SELECT pid FROM pg_stat_activity "
                        "WHERE application_name = %s AND pid <> pg_backend_pid()",
                        (binding.tag,),
                    )
                    pids = [int(row[0]) for row in cur.fetchall()]
                    if not pids:
                        return CancelResult(True, False, "control_connection", "执行句柄未找到或已结束")
                    confirmed = True
                    for pid in pids:
                        cur.execute("SELECT pg_cancel_backend(%s)", (pid,))
                        confirmed = bool(cur.fetchone()[0]) and confirmed
                    return CancelResult(True, confirmed, "pg_cancel_backend")

                # The SQL comment is generated below by tagged_sql. Match the
                # complete worker-owned tag before issuing KILL QUERY.
                cur.execute(
                    "SELECT ID FROM information_schema.PROCESSLIST WHERE INFO LIKE %s",
                    (f"/*{binding.tag}*/%",),
                )
                ids = [int(row[0]) for row in cur.fetchall()]
                if not ids:
                    return CancelResult(True, False, "control_connection", "执行句柄未找到或已结束")
                for server_id in ids:
                    cur.execute(f"KILL QUERY {server_id}")
                return CancelResult(True, True, "kill_query")
            finally:
                cur.close()
    except Exception as exc:
        text = str(exc)[:500]
        lowered = text.lower()
        denied = any(part in lowered for part in ("permission", "privilege", "access denied", "superuser"))
        return CancelResult(
            True,
            False,
            "control_connection",
            ("取消权限不足: " if denied else "取消未确认: ") + text,
        )


def cancel_run_execution(ds: DataSource, run_id: int, lease_token: str) -> CancelResult:
    """Cancel the currently registered statement without accepting a server PID."""
    with _registry_lock:
        bindings = [
            binding
            for binding in _registry
            if binding.run_id == run_id and binding.lease_token == lease_token
        ]
    for binding in bindings:
        result = _cancel_local(binding)
        if result and result.confirmed:
            return result

    kind = normalize_ds_type(ds)
    prefix = f"gido-adhoc:{run_id}:{lease_token}:"
    try:
        with open_connection(ds) as opened:
            cur = opened[1].cursor()
            try:
                if kind == "postgresql":
                    cur.execute(
                        "SELECT pid FROM pg_stat_activity "
                        "WHERE application_name LIKE %s AND pid <> pg_backend_pid()",
                        (prefix + "%",),
                    )
                    pids = [int(row[0]) for row in cur.fetchall()]
                    for pid in pids:
                        cur.execute("SELECT pg_cancel_backend(%s)", (pid,))
                    return CancelResult(
                        True, bool(pids), "pg_cancel_backend",
                        None if pids else "执行句柄未找到或已结束",
                    )
                cur.execute(
                    "SELECT ID FROM information_schema.PROCESSLIST WHERE INFO LIKE %s",
                    (f"/*{prefix}%",),
                )
                ids = [int(row[0]) for row in cur.fetchall()]
                for server_id in ids:
                    cur.execute(f"KILL QUERY {server_id}")
                return CancelResult(
                    True, bool(ids), "kill_query",
                    None if ids else "执行句柄未找到或已结束",
                )
            finally:
                cur.close()
    except Exception as exc:
        text = str(exc)[:500]
        denied = any(
            part in text.lower()
            for part in ("permission", "privilege", "access denied", "superuser")
        )
        return CancelResult(
            True,
            False,
            "control_connection",
            ("取消权限不足: " if denied else "取消未确认: ") + text,
        )


def tagged_sql(sql: str, binding: ExecutionBinding, ds_type: str) -> str:
    """Tag MySQL/Doris statements for cross-replica discovery."""
    if (ds_type or "").strip().lower() == "postgresql":
        return sql
    return f"/*{binding.tag}*/ {sql}"


def connection_query_id(connection: Any, ds_type: str) -> Optional[str]:
    """Return the stable server session identifier exposed by supported drivers."""
    kind = (ds_type or "").strip().lower()
    try:
        if kind == "postgresql":
            return str(connection.get_backend_pid())
        thread_id = getattr(connection, "thread_id", None)
        if callable(thread_id):
            return str(thread_id())
    except Exception:
        logger.debug("query identifier discovery failed", exc_info=True)
    return None


def is_server_timeout_error(exc: Exception) -> bool:
    text = str(exc).lower()
    return any(
        marker in text
        for marker in (
            "statement timeout",
            "statement_timeout",
            "max_execution_time",
            "query timeout",
            "query_timeout",
            "canceling statement due to",
            "execution was interrupted",
        )
    )
